# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop

#minecraft_version=26.1.2
#loader_version=0.19.2
#
#fabric_api_version=0.146.1+26.1.2
#modmenu_version=18.0.0-alpha.8
#clothconfig_version=26.1.154

#minecraft_version=26.1.1
#loader_version=0.19.2
#
#fabric_api_version=0.145.4+26.1.1
#modmenu_version=18.0.0-alpha.8
#clothconfig_version=26.1.154

minecraft_version=26.1
loader_version=0.18.4

fabric_api_version=0.144.0+26.1
modmenu_version=18.0.0-alpha.8
clothconfig_version=26.1.154

# Mod Properties
mod_version=1.1.5
maven_group=me.sootysplash
archives_base_name=optimalAim
